baseURL: 'https://hadrienmp.fr/'
languageCode: 'fr-fr'
title: 'HadrienMP'
theme: 'hadrienmp'

defaultContentLanguage: fr
languages:
  fr:
    weight: 1
  en:
    weight: 3


sectionPagesMenu: main

menu:
  main:
  - identifier: article
    name: Blog
    title: Blog
    url: /article/
    weight: 2
  - identifier: talk
    name: Talks
    title: Talks
    url: /talk/
    weight: 3
  - identifier: app
    name: Apps
    title: Apps
    url: /app/
    weight: 4

params:
  description: Hadrien Mens-Pellen, software crafter et coach. Développeur professionnel depuis 13 ans, je vous aide à créer et maintenir du code qui résiste à l'épreuve du temps.
  images:
  - ProfilDFuck.png

social:
  twitter: HadrienMP

markup:
  goldmark:
    renderer:
      unsafe: true
