baseURL: 'https://hadrienmp-hugo.onrender.com/'
languageCode: 'fr-fr'
title: 'HadrienMP'
theme: 'hadrienmp'

menu:
  main:
  - identifier: blogs
    name: Blog
    pre: <i class="las la-book"></i>
    url: /blog/
    weight: 3

params:
  description: Hadrien Mens-Pellen, software crafter et coach. Développeur professionnel depuis 13 ans, je vous aide à créer et maintenir du code qui résiste à l'épreuve du temps.

markup:
  goldmark:
    renderer:
      unsafe: true
