baseURL: 'https://hadrienmp-hugo.onrender.com/'
languageCode: 'fr-fr'
title: 'HadrienMP'
theme: 'hadrienmp'


sectionPagesMenu: main



params:
  description: Hadrien Mens-Pellen, software crafter et coach. Développeur professionnel depuis 13 ans, je vous aide à créer et maintenir du code qui résiste à l'épreuve du temps.
  images:
  - ProfilDFuck.png

social:
  twitter: HadrienMP

markup:
  goldmark:
    renderer:
      unsafe: true
